# Generated by Django 5.2.8 on 2025-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_document_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
