# Generated by Django 5.2.8 on 2025-11-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='edad',
            new_name='age',
        ),
    ]
